#
# Organisation configuration of SECURITY.md check policy.
#
# https://github.com/ossf/allstar/blob/main/README.md#securitymd
#
# Checks that the repository has a security policy file in
# SECURITY.md and that it is not empty.
  
# OptConfig is the org-level opt in/out config.
#
optConfig:
  optOutStrategy: false

# Action: defines which action to take.
# Valid values log|issue|fix. Default: log.
# https://github.com/ossf/allstar/blob/main/README.md#actions
#
action: issue
